#!/bin/sh
# Copyright 2009-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# provided by config-site
SITEDIR="/usr/share/confcache/include/site"

# user override
ETC_SITEDIR="/etc/confcache/include/site"

config_site_arch() {
	local host="${CHOST%%-*}"

	echo "${host}"
}

config_site_names() {
	local site_arch="$(config_site_arch)"
	local sites=""
	local x

	case ${CHOST} in
	*-linux-*)           sites="${sites} linux ${site_arch}-linux" ;;
	esac

	case ${CHOST} in
	*-linux-gnu*)        sites="${sites} linux-gnu ${site_arch}-linux-gnu" ;;
	esac

	for x in ${sites} ${CHOST}; do
		[ -e "${SITEDIR}/${x}" ] && echo "${SITEDIR}/${x}"
		[ -e "${ETC_SITEDIR}/${x}" ] && echo "${ETC_SITEDIR}/${x}"
	done
}

# crossdev handles cross ones separately (for now?), so only run for native
if [ "${CBUILD:-${CHOST}}" = "${CHOST}" ] ; then
	sites="$(config_site_names)"
	if [ -n "${sites}" ] ; then
		for site in ${sites}; do
			echo "${0##*/}: loading site script ${site}"
			. "${site}"
		done
	fi
	unset site sites
fi
